### ISSUE TITLE
不停的切换下面的Tab会到导致以下Exception

### ISSUE THREAD

**Issue by keyescgm** [tyzlmjj/PagerBottomTabStrip#3]
java.lang.IllegalStateException: No host
      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1235)
      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
      at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2042)
      at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1976)
      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1092)
      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
      at android.os.Handler.handleCallback(Handler.java:815)
      at android.os.Handler.dispatchMessage(Handler.java:104)
      at android.os.Looper.loop(Looper.java:194)
      at android.app.ActivityThread.main(ActivityThread.java:5636)
      at java.lang.reflect.Method.invoke(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:372)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)

**Comment by tyzlmjj** [comment]
这个不是导航栏的问题！这是因为我写测试代码的时候Fragment调用不规范，我加入了一个动画，这个动画导致产生了时间差，所以才导致这个错误。实际开发不会这样写Fragment!

**Comment by keyescgm** [comment]
那里的动画问题？因为我正好想写这样的组件，结果发现github上有，就看了看。。。
我的想法是用RadioGroup.addVew(RadioButton) 的方式，不过那个Oval就有点不好弄了;

**Comment by GreatGarlic** [comment]
@tyzlmjj 能否提供一下实际开发中的Fragment的写法？
