### ISSUE TITLE
开发者您好，作品很好，但是有个版本问题

### ISSUE THREAD

**Issue by wscjxky** [tyzlmjj/PagerBottomTabStrip#41]
在6.0以上的真机上使用良好
在5.1的模拟机中出现错误，闪退
 FATAL EXCEPTION: main
                                                                 Process: com.mage.magemata, PID: 6583
                                                                 java.lang.NoSuchMethodError: No virtual method getColor(I)I in class Lcom/mage/magemata/main/MainActivity; or its super classes (declaration of 'com.mage.magemata.main.MainActivity' appears in /data/app/com.mage.magemata-2/split_lib_slice_1_apk.apk)
                                                                     at com.mage.magemata.main.MainActivity.initData(MainActivity.java:59)
                                                                     at com.mage.magemata.main.BaseActivity.onCreate(BaseActivity.java:97)
                                                                     at android.app.Activity.performCreate(Activity.java:5990)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by wscjxky** [comment]
No virtual method getColor(I) 是我的失误
