### ISSUE TITLE
快速循环点击切换tab时抛异常

### ISSUE THREAD

**Issue by EsureZZZZZ** [tyzlmjj/PagerBottomTabStrip#5]
FATAL EXCEPTION: main
java.lang.IllegalStateException: No host
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1239)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
    at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2046)
    at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1989)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1092)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
    at android.os.Handler.handleCallback(Handler.java:725)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5039)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by MyGitHubOfZhao** [comment]
原来是Fragment的问题,重写下onDetch就没有异常了

**Comment by GreatGarlic** [comment]
@MyGitHubOfZhao 怎么重写，能否上传一下代码？

**Comment by MyGitHubOfZhao** [comment]
@Override
    public void onDetach() {
        super.onDetach();
        try {
            Field childFragmentManager = Fragment.class.getDeclaredField("mChildFragmentManager");
            childFragmentManager.setAccessible(true);
            childFragmentManager.set(this, null);
        } catch (NoSuchFieldException e) {
            throw new RuntimeException(e);
        } catch (IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }

**Comment by GreatGarlic** [comment]
@MyGitHubOfZhao thanks :)
