### ISSUE TITLE
偶尔会报数组越界的问题

### ISSUE THREAD

**Issue by returntoorigin** [tyzlmjj/PagerBottomTabStrip#61]
这是我的写法，很有可能是我不知道哪里写错了，能麻烦帮忙看一下：
List<?> shopTypeList = resultBean.getShopTypeList();
                PageNavigationView.CustomBuilder builder = pageTabLayout.custom();
                ArrayList<Fragment> fragments = new ArrayList<>();
                for (int i = 0; i < shopTypeList.size(); i++) {
                    ClassifyShopsFra classifyShopsFra = new ClassifyShopsFra();
                    Bundle bundle = new Bundle();
                    bundle.putString("shopTypeId", shopTypeList.get(i).getShopTypeId());
                    classifyShopsFra.setArguments(bundle);
                    fragments.add(classifyShopsFra);
                    builder.addItem(new OnlyTextTab(getActivity(), shopTypeList.get(i).getShopTypeName()));
                }
                adapter = new TypesPagerAdapter(getChildFragmentManager(), fragments);
                viewPager.setAdapter(adapter);
                NavigationController controller = builder.enableVerticalLayout().build();
                controller.setupWithViewPager(viewPager);

偶尔会出现以下错误，几率算是低吧。
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
    at java.util.ArrayList.get(ArrayList.java:437)
    at me.majiajie.pagerbottomtabstrip.internal.CustomItemVerticalLayout.setSelect(CustomItemVerticalLayout.java:151)
    at me.majiajie.pagerbottomtabstrip.internal.CustomItemVerticalLayout.setSelect(CustomItemVerticalLayout.java:125)
    at me.majiajie.pagerbottomtabstrip.NavigationController.setSelect(NavigationController.java:25)
    at me.majiajie.pagerbottomtabstrip.PageNavigationView.onRestoreInstanceState(PageNavigationView.java:657)
    at android.view.View.dispatchRestoreInstanceState(View.java:17819)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3773)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3781)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3781)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3781)
    at android.view.View.restoreHierarchyState(View.java:17797)
    at android.support.v4.app.Fragment.restoreViewState(Fragment.java:415)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1454)
    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
    at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:792)
    at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
    at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
    at android.os.Handler.handleCallback(Handler.java:808)
    at android.os.Handler.dispatchMessage(Handler.java:101)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7529)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by tyzlmjj** [comment]
没看出来问题在哪!如果数组越界，那就应该是你的页面数量和导航栏的按钮数量不对应。
你可以不用`setupWithViewPager `,用点击监听去实现页面切换，然后打印看看数据有没问题。

**Comment by returntoorigin** [comment]
> 没看出来问题在哪!如果数组越界，那就应该是你的页面数量和导航栏的按钮数量不对应。
> 你可以不用`setupWithViewPager `,用点击监听去实现页面切换，然后打印看看数据有没问题。

你的意思是在item的选中监听事件onSelected()中去创建Fragment还是说去调用ViewPager的setCurrentItem切换页面，(第一种每次都要去创建感觉太啰嗦了，第二种方法好像还是会出现上述问题，毕竟tab标签数和ViewPager页面数不一致，到时候还是会数组越界)，我现在很不解的是为什么在同一个for循环中添加的fragment和tab标签，他们数量为什么会不一样呢，看了源码也没发现有抛出异常不加入数组的代码，着实有点邪门。

**Comment by tyzlmjj** [comment]
应该是业务层面的逻辑问题，你再仔细查看下代码吧！
